### Q-2. Imagine you have a dataset where you have different features like Age,Gender , Height , Weight , BMI , and Blood Pressure and you have to classify the people into different classes like Normal , Overweight , Obesity , Underweight , and Extreme Obesity by using  any 4 different classification algorithms. Now you have to build a model which can classify people into different classes.

In [1]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('dataset/Obesity.csv')
df.head(10)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

We dont any any null values

In [3]:
for i in df.columns:
    print(len(df[i].unique()) , i , df[i].dtype)

2 Gender object
1402 Age float64
1574 Height float64
1525 Weight float64
2 family_history_with_overweight object
2 FAVC object
810 FCVC float64
635 NCP float64
4 CAEC object
2 SMOKE object
1268 CH2O float64
2 SCC object
1190 FAF float64
1129 TUE float64
4 CALC object
5 MTRANS object
7 NObeyesdad object

In [4]:
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [5]:
y = df['NObeyesdad']
if 'NObeyesdad' in df.columns:
    df.drop('NObeyesdad' , inplace = True , axis = 1)
    
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
y

array([1, 1, 1, ..., 4, 4, 4])

#### we will apply onehotencoder on every categorical columns

In [7]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output= False)
df_cat = ohe.fit_transform(df.select_dtypes(include = 'O'))

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df_cat = sc.fit_transform(df_cat)

In [9]:
df_cat = pd.DataFrame(df_cat, columns = ohe.get_feature_names_out())

In [10]:



df_num = sc.fit_transform(df.select_dtypes(include = 'number'))

In [11]:
df_num = pd.DataFrame(df_num , columns = sc.get_feature_names_out())
df_num

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
0,-0.522124,-0.875589,-0.862558,-0.785019,0.404153,-0.013073,-1.188039,0.561997
1,-0.522124,-1.947599,-1.168077,1.088342,0.404153,1.618759,2.339750,-1.080625
2,-0.206889,1.054029,-0.366090,-0.785019,0.404153,-0.013073,1.163820,0.561997
3,0.423582,1.054029,0.015808,1.088342,0.404153,-0.013073,1.163820,-1.080625
4,-0.364507,0.839627,0.122740,-0.785019,-2.167023,-0.013073,-1.188039,-1.080625
...,...,...,...,...,...,...,...,...
2106,-0.525774,0.097045,1.711763,1.088342,0.404153,-0.456705,0.783135,0.407996
2107,-0.367195,0.502844,1.800914,1.088342,0.404153,-0.004702,0.389341,-0.096251
2108,-0.281909,0.541672,1.798868,1.088342,0.404153,0.075361,0.474971,-0.019018
2109,0.007776,0.404927,1.785780,1.088342,0.404153,1.377801,0.151471,-0.117991
2110,-0.102119,0.398344,1.790592,1.088342,0.404153,1.396035,0.018996,0.092432

In [12]:
df_transformed = pd.concat([df_num , df_cat] , axis = 1)
df_transformed

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender_Female,Gender_Male,...,SCC_yes,CALC_Always,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,-0.522124,-0.875589,-0.862558,-0.785019,0.404153,-0.013073,-1.188039,0.561997,1.011914,-1.011914,...,-0.218272,-0.02177,-0.185194,-1.404720,1.517761,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
1,-0.522124,-1.947599,-1.168077,1.088342,0.404153,1.618759,2.339750,-1.080625,1.011914,-1.011914,...,4.581439,-0.02177,-0.185194,0.711885,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
2,-0.206889,1.054029,-0.366090,-0.785019,0.404153,-0.013073,1.163820,0.561997,-0.988227,0.988227,...,-0.218272,-0.02177,5.399735,-1.404720,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
3,0.423582,1.054029,0.015808,1.088342,0.404153,-0.013073,1.163820,-1.080625,-0.988227,0.988227,...,-0.218272,-0.02177,5.399735,-1.404720,-0.658865,-0.525642,-0.05768,-0.072375,-1.724969,6.057758
4,-0.364507,0.839627,0.122740,-0.785019,-2.167023,-0.013073,-1.188039,-1.080625,-0.988227,0.988227,...,-0.218272,-0.02177,-0.185194,0.711885,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,-0.525774,0.097045,1.711763,1.088342,0.404153,-0.456705,0.783135,0.407996,1.011914,-1.011914,...,-0.218272,-0.02177,-0.185194,0.711885,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
2107,-0.367195,0.502844,1.800914,1.088342,0.404153,-0.004702,0.389341,-0.096251,1.011914,-1.011914,...,-0.218272,-0.02177,-0.185194,0.711885,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
2108,-0.281909,0.541672,1.798868,1.088342,0.404153,0.075361,0.474971,-0.019018,1.011914,-1.011914,...,-0.218272,-0.02177,-0.185194,0.711885,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
2109,0.007776,0.404927,1.785780,1.088342,0.404153,1.377801,0.151471,-0.117991,1.011914,-1.011914,...,-0.218272,-0.02177,-0.185194,0.711885,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078
2110,-0.102119,0.398344,1.790592,1.088342,0.404153,1.396035,0.018996,0.092432,1.011914,-1.011914,...,-0.218272,-0.02177,-0.185194,0.711885,-0.658865,-0.525642,-0.05768,-0.072375,0.579721,-0.165078

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X_train , X_test , y_train , y_test = train_test_split(df_transformed , y, test_size = 0.2 , random_state = 45)
# Define the parameter grids for each model
random_forest_params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
}

logistic_regression_params = {
    'C': [0.1, 1.0, 10.0],
    'solver': ['liblinear', 'saga'],
    'max_iter':[1000000]
}

svm_params = {
    'C': [1.0, 10.0, 100.0],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto'],
    'max_iter':[1000000]
}

decision_tree_params = {
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
}

knn_params = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance'],
}

# Generate random parameters for each model


# Create GridSearchCV objects for each model
random_forest_grid_search = GridSearchCV(RandomForestClassifier(), random_forest_params , cv = 5 , scoring = 'accuracy')
logistic_regression_grid_search = GridSearchCV(LogisticRegression(), logistic_regression_params , cv = 5,  scoring = 'accuracy')
svm_grid_search = GridSearchCV(SVC(), svm_params , cv = 5,   scoring = 'accuracy')
decision_tree_grid_search = GridSearchCV(DecisionTreeClassifier(), decision_tree_params , cv =5,  scoring = 'accuracy')
knn_grid_search = GridSearchCV(KNeighborsClassifier(), knn_params ,cv = 5,  scoring = 'accuracy')



# Print the random parameter grids for each model
print("Random Parameter Grid for Random Forest:")
print(random_forest_grid_search.param_grid)
print()

print("Random Parameter Grid for Logistic Regression:")
print(logistic_regression_grid_search.param_grid)
print()

print("Random Parameter Grid for SVM:")
print(svm_grid_search.param_grid)
print()

print("Random Parameter Grid for Decision Tree:")
print(decision_tree_grid_search.param_grid)
print()

print("Random Parameter Grid for KNN:")
print(knn_grid_search.param_grid)

Random Parameter Grid for Random Forest:
{'n_estimators': [100, 200, 300], 'max_depth': [None, 5, 10], 'min_samples_split': [2, 5, 10]}

Random Parameter Grid for Logistic Regression:
{'C': [0.1, 1.0, 10.0], 'solver': ['liblinear', 'saga'], 'max_iter': [1000000]}

Random Parameter Grid for SVM:
{'C': [1.0, 10.0, 100.0], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto'], 'max_iter': [1000000]}

Random Parameter Grid for Decision Tree:
{'max_depth': [None, 5, 10], 'min_samples_split': [2, 5, 10]}

Random Parameter Grid for KNN:
{'n_neighbors': [3, 5, 7], 'weights': ['uniform', 'distance']}

In [14]:
# Lets start Training
models = [random_forest_grid_search, random_forest_grid_search, logistic_regression_grid_search ,svm_grid_search, decision_tree_grid_search, knn_grid_search]
for model in models:
    model.fit(X_train , y_train)
    y_pred = model.predict(X_test)
    score = accuracy_score(y_test , y_pred)
    print(f'{model.best_estimator_ ,model.best_params_ } \n')
    print(f'Training Score : {model.best_score_ } , Validation Score : {score} \n')

## As per results we can creat model of svm , and deploy

In [20]:
svc = SVC(C= 100.0, gamma= 'scale', kernel= 'linear', max_iter= 1000000)
svc.fit(X_train , y_train)
y_pred = svc.predict(X_test)
score = accuracy_score(y_pred , y_test)

c:\Users\nitin\anaconda3\envs\alma\lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=1000000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

In [21]:
score

0.9527186761229315